# -*- coding: utf-8 -*-
"""google-drive.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s2KNRboRBPShtfwry9znYWH--KedFivg
"""

from google.colab import drive
drive.mount('/content/drive')

# import os
# os.environ['MODEL_ROOT'] = userdata.get('/content/drive/MyDrive/hf-models')

# 挂载后，您可以通过以下方式访问您的文件，例如：
# import pandas as pd
# df = pd.read_csv('/content/drive/MyDrive/YourFolder/your_data.csv')
# display(df.head())

# @title
!git clone https://github.com/jetsung/colab.git

# Commented out IPython magic to ensure Python compatibility.
# %cd colab

!make setup

!curl -L -o /usr/bin/direnv https://github.com/direnv/direnv/releases/download/v2.37.1/direnv.linux-amd64 && chmod +x /usr/bin/direnv && direnv --version

!make install-llama-build

import os
from google.colab import userdata
os.environ['HF_TOKEN'] = userdata.get('HF_TOKEN')
os.environ['API_KEY'] = userdata.get('API_KEY')
os.environ['BORE_SECRET'] = userdata.get('BORE_SECRET')
os.environ['BORE_SERVER'] = userdata.get('BORE_SERVER')

!echo $HF_TOKEN
!echo $API_KEY
!echo $BORE_SECRET
!echo $BORE_SERVER
!echo $MODEL_ROOT

!https://github.com/direnv/direnv/releases/download/v2.37.1/direnv.linux-amd64

# Commented out IPython magic to ensure Python compatibility.
# %env LLAMA_MODEL_REPO=unsloth/Qwen3.8-27B-GGUF
#%env LLAMA_QUANT=UD-Q8_K_XL
# %env LLAMA_QUANT=BF16

!make llama-start

!make llama-status

!make llama-stop

!make llama-logs

!make bore-start

!make bore-status

!make bore-stop

!make bore-logs

!make sglang-logs

import os

repo = os.environ.get('LLAMA_MODEL_REPO', '')
_repo_name = repo.rsplit('/', 1)[-1]       # 等价于 ${LLAMA_MODEL_REPO##*/}
_model_name = _repo_name.removesuffix('-GGUF')  # 等价于 ${_repo_name%-GGUF}

os.environ['_model_name'] = _model_name
print(f"✅ _model_name = {_model_name}")

# Commented out IPython magic to ensure Python compatibility.
# %env MODEL_ROOT=/content/drive/MyDrive/hf-models

! curl -fsSL http://localhost:30000/v1/chat/completions \
    -H "Authorization: Bearer $API_KEY" \
    -H "Content-Type: application/json" \
    -d '{"model":"'$_model_name'","messages":[{"role":"user","content":"你好，你是什么底层模型？即 qwen 哪个版本？"}],"max_tokens":256}' \
      | jq -r .

!cat .envrc

!cat llama/.env.g4

!ls -lah /content/drive/MyDrive/hf-models/Qwen3.8-27B-GGUF/BF16